### ISSUE TITLE
WHAT ABOUT MEEEEEEEEEEEEEE

### ISSUE THREAD

**Issue by Thyraxis** [surepy/tf2db-sleepy-list#1]
![image](https://github.com/surepy/tf2db-sleepy-list/assets/132177323/8a4c6c7a-5d3c-4897-b8a2-7232ca533d73)
cough cough
https://steamcommunity.com/groups/thyboatreal/members

**Comment by sydenlous** [comment]
so true

**Comment by sydenlous** [comment]
> ![image](https://user-images.githubusercontent.com/132177323/238053866-8a4c6c7a-5d3c-4897-b8a2-7232ca533d73.png) cough cough https://steamcommunity.com/groups/thyboatreal/members

you dont have enough bots!!!!!!!!!!!!!!!! make more!!!!!!

**Comment by surepy** [comment]
> > ![image](https://user-images.githubusercontent.com/132177323/238053866-8a4c6c7a-5d3c-4897-b8a2-7232ca533d73.png) cough cough https://steamcommunity.com/groups/thyboatreal/members
> 
> you dont have enough bots!!!!!!!!!!!!!!!! make more!!!!!!

+1 

host's skill and pc issue, host more that I actually see it in my mm games.

**Comment by surepy** [comment]
also damn, cathook ipc got a UI overhaul? when?

it isn't the shitty green table that looks like from the 90s anymore when i used it that's crazy
