### ISSUE TITLE
Sydney bots

### ISSUE THREAD

**Issue by sydenlous** [surepy/tf2db-sleepy-list#2]
they are all legit players i have lots of friends
if you dont remove them i will send a nuclear bomb to your exact location

**Comment by sydenlous** [comment]
also you dont have the lmaobox bots on here u suck

**Comment by surepy** [comment]
dont have the lbox bots here cuz i didnt see them /shrug

a nuclear bomb would be pretty nice tbh gonna sell it on aliexpress for pretty good bucks
