### ISSUE TITLE
WHAT ABOUT TROLLSEC BOTS U LEGITFAG LMFAO

### ISSUE THREAD

**Issue by TrollSECReality** [surepy/tf2db-sleepy-list#3]
LLLLL DIDNT EVEN FIND MY MAIN RETARD LMFAO

omg guys he found my vacced profile!!!11111

IM GONNA GET COMMUNITY BANNED NO!!!!!!!!11

**Comment by snipergaming888** [comment]
NOOOO PLEASE DONT BAN TROLLSEC DUDE

**Comment by snipergaming888** [comment]
also i like how he completely ignored my group that i am in

**Comment by TrollSECReality** [comment]
> also i like how he completely ignored my group that i am in lol

guys legits are so hurtfull!!!! storing our steam ids !!!! THEYRE GOING TO HAXXOR INTO MY ASSHOLE!!!!! OH NO!!!111

**Comment by surepy** [comment]
idk u were just there in friendslist so I just added, it only took a couple second of my time.

I'm not doing more than 10 seconds of research on some noname to find and search your main. I _really_ don't care that much.

**Comment by surepy** [comment]
> also i like how he completely ignored my group that i am in lol

I've already spent enough time just converting ur friendslist into json and rejecting possible false positives, any more was already not worth my time.
