### ISSUE TITLE
false positives on playerlist.sleepy-bots.qt.json 

### ISSUE THREAD

**Issue by programmedsun** [surepy/tf2db-sleepy-list#5]
Its not a great idea to automatically mark normal TF2 players who doesnt cheat as cheaters just because they joined a stupid steam group.

**Comment by surepy** [comment]
will look into it in a bit (I'm not home)

I'm aware of that issue but sometimes (as the description says) I'm incredibly lazy.

**Comment by surepy** [comment]
fixed, thanks.

**Comment by sydenlous** [comment]
i do believe i am not a bot aswell

**Comment by ghost** [comment]
> i do believe i am not a bot aswell

same

**Comment by qtTF2** [comment]
> fixed, thanks.

Can u remove me from the list, my steam id is 76561199482717511 [1522451783]?
