### ISSUE TITLE
Steam ID removal request

### ISSUE THREAD

**Issue by programmedsun** [surepy/tf2db-sleepy-list#6]
Hello surepy,
I am requesting if you can remove my steam id 76561199482717511 [U:1:1522451783] from the list playerlist.sleepy-bots.qt.json as I do not feel comfortable having my steam ID on that list.

**Comment by surepy** [comment]
sorry, I can't do that.

the most I can do for you is move you to either to the main sleepylist or external. 

honestly don't worry too much though, not many people use my list anyways (its mainly for myself to keep as a note of "what this person is") and gaslighting people in tf2 lobbies are incredibly easy anyway.

you should honestly be more concerned about the uncletopia/"trusted" list.
